#!/bin/bash
# Pleng installer — from zero to your own cloud in one command.
# Usage: curl -fsSL https://raw.githubusercontent.com/mutonby/pleng/main/install.sh | bash
#
# Requires: Ubuntu 22.04+ with root/sudo access, ports 80 and 443 open.

set -euo pipefail

# When piped from curl, stdin is the pipe — redirect reads to the terminal
exec 3</dev/tty 2>/dev/null || exec 3<&0

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}→${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; exit 1; }
header() { echo -e "\n${BOLD}$1${NC}"; }
ask()   { echo -ne "${CYAN}$1${NC} "; read -r "$2" <&3; }

# ── Checks ─────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
    error "Run as root: curl -fsSL ... | sudo bash"
fi

if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then
    error "This installer is for Ubuntu only (22.04+)"
fi

header "🚀 Pleng Installer"
echo "Your AI Platform Engineer — one VPS, one command, your own cloud."
echo ""

# ── Install Docker ─────────────────────────────────────

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    ok "Docker + Compose already installed"
else
    header "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg >/dev/null 2>&1
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null 2>&1
    systemctl enable --now docker >/dev/null 2>&1
    ok "Docker installed"
fi

# ── Install Git ────────────────────────────────────────

if ! command -v git &>/dev/null; then
    info "Installing git..."
    apt-get install -y -qq git >/dev/null 2>&1
    ok "Git installed"
fi

# ── Clone Pleng ────────────────────────────────────────

INSTALL_DIR="/opt/pleng"

if [ -d "$INSTALL_DIR/pleng" ]; then
    info "Pleng already cloned at $INSTALL_DIR/pleng — pulling latest..."
    cd "$INSTALL_DIR/pleng"
    git pull --ff-only 2>/dev/null || true
else
    header "Cloning Pleng..."
    mkdir -p "$INSTALL_DIR"
    git clone https://github.com/mutonby/pleng "$INSTALL_DIR/pleng"
    cd "$INSTALL_DIR/pleng"
    ok "Cloned to $INSTALL_DIR/pleng"
fi

# ── Gather config ──────────────────────────────────────

header "Configuration"

# Detect public IP
DETECTED_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || curl -s --max-time 5 icanhazip.com 2>/dev/null || echo "")

if [ -f .env ] && [ -s .env ]; then
    ask "Existing .env found. Overwrite? (y/N):" OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        ok "Keeping existing .env"
        SKIP_ENV=true
    fi
fi

if [ "${SKIP_ENV:-}" != "true" ]; then

    # ── Step 1: Telegram bot token ─────────────────────
    header "Step 1 — Telegram Bot"
    echo "You need a Telegram bot. It takes 30 seconds:"
    echo ""
    echo "  1. Open Telegram and search for @BotFather"
    echo "  2. Send: /newbot"
    echo "  3. Choose a name (e.g. \"My Pleng\")"
    echo "  4. Choose a username (e.g. \"my_pleng_bot\")"
    echo "  5. BotFather gives you a token like: 123456:ABC-DEF..."
    echo ""
    ask "Paste your bot token here:" TELEGRAM_BOT_TOKEN
    [ -z "$TELEGRAM_BOT_TOKEN" ] && error "Bot token is required"
    ok "Bot token saved"

    # ── Step 2: Chat ID ────────────────────────────────
    echo ""
    header "Step 2 — Your Chat ID"
    echo "The bot will only respond to YOU. We need your chat ID:"
    echo ""
    echo "  1. Open Telegram and search for @userinfobot"
    echo "  2. Send: /start"
    echo "  3. It replies with your ID (a number like 123456789)"
    echo ""
    ask "Paste your chat ID here:" TELEGRAM_CHAT_ID
    [ -z "$TELEGRAM_CHAT_ID" ] && error "Chat ID is required"
    ok "Chat ID saved"

    # ── Step 3: Server config ──────────────────────────
    echo ""
    header "Step 3 — Server"

    ask "VPS public IP [$DETECTED_IP]:" PUBLIC_IP
    PUBLIC_IP=${PUBLIC_IP:-$DETECTED_IP}
    [ -z "$PUBLIC_IP" ] && error "Public IP is required"

    ask "Email for SSL certs:" ACME_EMAIL
    [ -z "$ACME_EMAIL" ] && error "Email is required for Let's Encrypt"

    ask "Dashboard password [auto-generated]:" WEB_UI_PASSWORD
    WEB_UI_PASSWORD=${WEB_UI_PASSWORD:-$(openssl rand -hex 8 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 16)}

    # Write .env
    cat > .env << ENVFILE
# Generated by Pleng installer — $(date -u +"%Y-%m-%d %H:%M UTC")
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
PUBLIC_IP=$PUBLIC_IP
ACME_EMAIL=$ACME_EMAIL
WEB_UI_PASSWORD=$WEB_UI_PASSWORD
PROJECTS_PATH=/opt/pleng/projects
MODEL_NAME=claude-sonnet-4-20250514
ENVFILE

    ok ".env created"
fi

# ── Create directories ─────────────────────────────────

mkdir -p /opt/pleng/projects /opt/pleng/backups
ok "Directories ready"

# ── Prepare OAuth mounts ───────────────────────────────

# Docker creates directories for missing bind mounts — prevent that
mkdir -p ~/.claude
[ ! -f ~/.claude.json ] && echo '{}' > ~/.claude.json

# ── Create Docker network ──────────────────────────────

docker network create pleng_web 2>/dev/null || true

# ── Start Pleng ────────────────────────────────────────

header "Starting Pleng..."
docker compose up -d --build 2>&1 | tail -5

# Wait for platform-api to be healthy
info "Waiting for platform-api to be ready..."
READY=false
for i in $(seq 1 30); do
    if docker compose exec -T platform-api python -c "import requests; requests.get('http://localhost:8000/api/health', timeout=3)" 2>/dev/null; then
        READY=true
        break
    fi
    sleep 2
done

if [ "$READY" = true ]; then
    ok "Pleng is running"
else
    echo ""
    info "Platform API is still starting. Check logs with: docker compose logs -f platform-api"
fi

# ── Claude Code login ──────────────────────────────────

header "Claude Code Authentication"
echo "Claude Code will guide you through login."
echo "You can use your Pro/Max subscription or an API key."
echo ""

# Wait for agent container to be ready
info "Waiting for agent to be ready..."
for i in $(seq 1 30); do
    if docker compose exec -T agent curl -sf http://localhost:8000/health 2>/dev/null; then
        break
    fi
    sleep 3
done

# Launch interactive login — stdin from /dev/tty for user input
docker compose exec -it agent sudo -u claude env HOME=/home/claude claude /login </dev/tty || true

ok "Authentication complete"

# ── Summary ────────────────────────────────────────────

PASS=$(grep WEB_UI_PASSWORD .env | cut -d= -f2)
IP=$(grep PUBLIC_IP .env | cut -d= -f2)

echo ""
header "═══════════════════════════════════════════════"
header "  Pleng is ready!"
header "═══════════════════════════════════════════════"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  http://panel.${IP}.sslip.io"
echo -e "  ${BOLD}Password:${NC}   ${PASS}"
echo -e "  ${BOLD}Telegram:${NC}   Message your bot — say \"hello\""
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo "  cd $INSTALL_DIR/pleng"
echo "  make logs        # View all logs"
echo "  make ps          # Container status"
echo "  make chat        # Terminal chat with agent"
echo ""
echo -e "  ${GREEN}Your own cloud is live. Talk to it.${NC}"
echo ""
